[build-system]
requires = ["uv_build>=0.11.9,<0.12"]
build-backend = "uv_build"

[project]
name = "flippr"
version = "0.3.0"
description = "FragPipe Limited-Proteolysis Processor (FLiPPR) is modular, fast, and easy-to-use data processing tool for LiP-MS & LFQ-based experiments analyzed in FragPipe"
readme = "README.md"
requires-python = ">=3.12"

keywords = [
  "computational mass spectrometry",
  "fragpipe",
  "limited proteolysis",
  "lip-ms",
  "lfq",
  "label-free quantification",
  "differential analysis",
  "proteomics",
  "flippr",
]

authors = [
  { name = "Edgar Manriquez-Sandoval", email = "mansanlab@gmail.com"},
]

maintainers = [
  {name = "FriedLab@JHU", email = "friedlab.jhu@gmail.com"},
  {name = "Stephen D. Fried", email = "sdfried@jhu.edu"},
  {name = "Edgar Manriquez-Sandoval", email = "mansanlab@gmail.com"},
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]

dependencies = [
  "numpy>=2.3",
  "polars>=1.33",
  "scipy>=1.16",
]

[project.urls]
Documentation = "https://github.com/FriedLabJHU/FragPipe-Limited-Proteolysis-Processor#readme"
Issues = "https://github.com/FriedLabJHU/FragPipe-Limited-Proteolysis-Processor/issues"
Source = "https://github.com/FriedLabJHU/FragPipe-Limited-Proteolysis-Processor"

[dependency-groups]
dev = [
  "coverage[toml]>=7.6",
  "mypy>=1.14",
  "pytest>=8.3",
]
docs = [
  "sphinx>=8.1",
  "sphinx-rtd-theme>=3.0",
]

[tool.uv]
default-groups = ["dev"]

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "scipy"
ignore_missing_imports = true

[tool.coverage.run]
source_pkgs = ["flippr", "tests"]
branch = true
parallel = true
omit = [
  "src/flippr/__about__.py",
]

[tool.coverage.paths]
flippr = ["src/flippr", "*/flippr/src/flippr"]
tests = ["tests", "*/flippr/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
